export class Video{
	id:number;
	title:string;
	plot:string;
	type:string;
	languages:string;
	genres:string;
	video_path:string;
	released:string;
	runtime:string;
	director:string;
	writer:string;
	actors:string;
	country:string;
	awards:string;
	poster_api:string;
	poster_path:string;
	rating:string;
	votes:string;
	imdburl:string;
}